#!/bin/bash
#echo dji | sudo -S cpufreq-set -g performance
#echo -e "gnome-terminal -- bash -c \"/home/nvidia/Desktop/a_miaosuan_v6.3.1_new_watcher/tools/monitor.sh\"">>~/.profile
/home/nvidia/Desktop/a_miaosuan_v6.3.1_height_watcher/build/run
